---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCar0NqXvkdEMuRfPkvd0eClHNhATGZOnY2eQlpQC/gYO1QzzZtwNrZhV2OcpJUl4I0Vc4WbB+YLnKSwqDXxZm2R8OQSh2kl152djZs+E37RTg0XN0BrWVONL4R8SG+P8IZMsHgk4amRXn2jV0+Hu3QvtoaXqzY2nUZhUPXQSmEWh7mcE/IBdy7fh7ZrbQ59V1Re8N81NOC47hRvtUD66eqHPC9pgtXEkzsAlGGwVRCz5Hzwu68U94KW9X2rc3sGbHHQdE3yK2tfX4UEM7oI740OjurRVwzSKVebUNOxORkWe4psZ7d7RgP4zD+71+QWM9anuAZ8TrlpeUqWpSn31sf43MOBdNtezu21684nk5v379U1g7BIDoQx0a+V1rBkLHVAKbGY82OFO3murUZHLV1T+4KJOH9R1B1lLenKXoKv4hQOpAOMuPxaEkSstJ4i6s4QQAgWRW8GyRymow/lk3Un6VXA3HYy1IX1u9I7sbO8X58uZFFiej5eyT6xQ/9OOlrdBVXfTSwS7iJc1r2FTAOdCjHQZEc7VGRA98+Datt16BP7uzHITJXwb+qTRnIGNTndeaTXWlro+nW7atejk0kkpLTSp6z8V/iGPeuaM4uMG8/JGMUZ5mS0BDCE/L7mHfr9yLNkiAfduPCaSYkqxOFyvFyBbg6IEPZ02L4m0GIToyukcw7kcP1a8mjC8qkQHN8HOLK9Xz6ng==
    DB_USER: AgBc7bIhYz9QsdLot1lwqBuJ4fxkJOBuEIApmh7coZNfJgoOVWDvgQIH7od1i6rhBAlKwex3NSGAFAEjzuTOyJwGq4J7QTbV6+DK22ILIYS6R2CYVeB8ng38bzQzqBxNg3bIysXa9YBYxDFCFN3JotEx7oKcAJbymYPWyKTLvdw2BFCzxczyJe8ynS1uW2palX3HdBQVJjRUbkp/TqE/LCYV39EqK2Pyz0NjCiSLQmCMfbUBSFcb4AP+lY0ZdEjCnbX8QpeEh5eaax9wALC+w0Z8Kmh/vX33X9KrsHV3+E+Ay15HngFswlHwd7MVqqvl47O51TiaPCUl0WZW2E29fwB+MjsFzZ0+lJrtaEP4VzWeRqj2V2wl6u5cf5iuyMQ6ZJLi0/ODb6uoliO79nk0bbWL89UAvAmR9N0FAESAAifjK2BcSsn0WPjeswukGj9oYjBASXbYNQCfH32wClYmXNcJ4+Bpu9iZxDI6fPU+6Wzp7SzjM9NdjC9j8DQOxiVLtByV9EWybs5mddn3WgQyUfZaWVC4SwHw3cMtsK4JXyLYWuECKNgHHrbgTYX/18RFgEqyywrk28t6adz7gE2+Qw8Gm9ksq4/e61wlugcjAQo1HK/gOVE+tXHGLylLr2gQnM8b3GNm26PdvcXNdTAsXoKBUE1W2qSPjkmRjGCFP9Z7uovNNXdQQ9SYAXgI/tt9LsZqyEpGK0COtA==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque
