---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAmq9tgqJ9nYiJDkHy1iO5XvATrA7v81bZP3oqrAI9tsIAxGxpPN1h9WfVwewy9lbFp4cjU95uv0IU9VZIm+hY9hn8YwabtG4SAq/Dj1J+tfaRsDCKc/a2sRrgTOJeDJ7Vuo18ZOJFmATxo/U7BOjION7gO2w9EpGLSohO7mveZSx9Dsvzc+NCvaKrj7RiL341rogIHPyrmKxARzaPQo1tT/74aOxGfpBPlgXTWZk44GVsc8sacMpOYE4fyE71SfNTnZqX1kfY0fwIqP5EIPcRGw3hM7/EOxUlU1aJtjezYCR6u08sSXPnXJSJlzUJcI+tRN9okGGkJ/gSoNpYLmB8hISKZEh5Jz/KwvH4m3VQD+fsiEwhug9ZAmRDXIZZ3MytittQxcyceh/KnIVAyUO+Z6G0+ZKCxGaci4pHQWtlhxcR2FKyRn4DIPhZZzAbwYFHSBmDti9NPBbbek3LnrAe1R4vhOGAtdMMVXr1iW01F9R4/vW5gTRQ13mvKT5izD3nIarsmH2XI0qfcuTxLM+WPPm0O31ciYdQhh29sSZgFfbtOQS51U8AX5oKgJd3GjcT2Mpf9GTZOey2mgAjBIwBcbUa7E+vQXTaKDLFpsVDLEKafegP/Le/yMWU6hnnVE99++lJ3/YGJpWFag1erPjSrkNcqhIrrgk/GV+tjsFFwKpJm97UsQxds4P22MeSFHG0MuLOiSMs1ng==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque
