---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBTywvdc+Sn9BpSg49+2M41vEOrpznZkk99GoNFh3T8kWLVxDPHmDRvmjjsLno42Ajp6R1BVaoEMq0b1ZfFgJnKZAA3SUU3q+/SB2BZ72GT34AWtZ/EURfgOTihZgAnX2L5zouAPEf5yU/wy4k55jJgrYbX3W6dIx1LsW7r0u4KDvM0rRL90PkFYrr3MFREGggrEmUUUTadqrh0n+ta4OU6pqVmF9vEWE65d/REYhj/eg1fRKo3jCNJJFPqTcTly/GN4FszkL1dvqeZFbnUmQ8xOcxpSvRPvf2IJYsRJzBi28FOnyF2kY7d0giZiXiHiovo1ElknyGSjLg5dxjkrO77E1Wiq5Qc6DGpZvxBXxLSQSF/dkIEbHxJ7x+mPychEoSmj7y8dKSgzOtxSknYu99k3lv99qU8Zx0bmhlldtxs2GaYrfJnqWHx0vkegXlr+o2nvbE9wdnqOpzG1OwyjvywEws42/CHro5JIfaFOwyRCRrQ/7xBAVe6s0/O6GUS+YUuPXTsCRHD/oqe7KSWo2Hia90Ia8vB0U70mdhlONP9VOc4oTB4Z5nQwCDX4093G5zfgt3mRh8ZanbIVwXq/EmADgu7swAS46u5Svf+a72y4FHLxSh3WIpp+fhkVY7EIzRYoGhHvVHZ/79NyJwcV6FspAT2Cb3NxgVpvh0EFnYLwX5qEuOCqnpw5TCSvAY0Kh1KapCO+USuTA==
    DB_USER: AgBG3Be0+PelyZRtlaO6UDVvLhfgl5tsiRt6KbRI/h+tqlMf31CA6DeTuVWFXGl0eHnUj3Ynsq4V2/IVHQmELaXjk99lH6tAqP7CR0uCLsjExv4rAtOmPLr3P0xH4ia/ZBsJAQmTs6zCy8w5bUEeHHrmUPFcbN3ntIxAYiBTHNDXJB5m33HHHIZ2nM09IX5VG3+3G1k9Srzxs6NsZ8V0vsnFSdqyKSaVenZ1PpRXt4vhzbiwzOVfQT0r+3xA7ZVeVhpOEDcX8u7XM72wyWpbCp0LkjzVwa+BNT4Fm6MUZR5FedGKHYmXSmROXlhn/fWmWtab1UZNfMyj1/YbMUOf5lNL5EJ84WbIcGqIb1ujd0cHI7aiiablcj3czekxZner+8i34pJW4x5v1xA53aSLUsu9baDeqwv5gM3e3ROwyQQo7lwegciCw4hfyQEp+AGPoUcxpRkvC6Lpeb7t6CFRp2kRrwHZOLJqhEY7arkx3qpKMZZB9J3UKb4ZabAO6X5esQVootem3G5O4b1omXhusjszH303knjymVVTeNbxZ4hVZFXtchYyyYRzswijPAN2COnd/RO2LeKQNgqR0fuKNYWED3Mrwez/kGQLBSy5dKqSDdXm/HRDspqfxz4rU6ytIryA1C4DM0mTz58g+AL6tTOY8nqHLR2vIEIT3sRfc9sdqA2A8sdabNanAuzHVROwk3Td1nQTEf4qtg==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque
